# 仕様書作成支援ボット - プロンプト設定
# このファイルでエージェントの応答品質をチューニングできます

# エージェント関連プロンプト
agent:
  # システムメッセージ - 簡素化版
  system_message: |
    あなたは仕様書作成支援ボットです。
    
    ユーザーの質問に対して、利用可能なツールを使って情報を検索し、
    検索結果に基づいて詳細で有用な回答を提供してください。
    
    必ず検索を実行してから、見つかった情報を基に回答してください。

  # ReActテンプレート - 最小限版
  react_template: |
    Answer the following questions as best you can. You have access to the following tools:

    {tools}

    Use the following format:

    Question: the input question you must answer
    Thought: I should search for information about this topic
    Action: {tool_names}
    Action Input: search query
    Observation: the result of the action
    Thought: I now know the final answer
    Final Answer: Based on the search results, here is my answer: [detailed response]

    Begin!

    Question: {input}
    Thought:{agent_scratchpad}

# ツール説明文 - LLMがツールを適切に選択できるよう最適化
tools:
  jira_search:
    name: "jira_search"
    description: |
      🎯 Jiraチケットをキーワードで検索し、詳細な情報を取得します。
      
      【使用場面】
      ・「○○のバグを探して」「進捗を確認したい」
      ・「ログイン機能のチケット」「UIに関するタスク」
      ・「担当者のチケット一覧」「プロジェクトの状況」
      
      【入力】ユーザーの質問から抽出した検索キーワード（日本語OK）
      【出力】関連チケットの詳細情報（タイトル、ステータス、担当者、説明、リンク付き）
      
      【重要】検索結果は件数だけでなく、各チケットの内容を分析して具体的な情報を抽出すること

  confluence_search:
    name: "confluence_search"
    description: |
      📚 Confluenceドキュメントをキーワードで検索し、内容を詳細分析します。
      
      【使用場面】
      ・「仕様書を探して」「設計書を見たい」
      ・「議事録を確認したい」「○○の手順書」
      ・「技術文書」「マニュアル」「プロジェクト資料」
      ・「最適な○○について」「ベストプラクティス」
      
      【入力】ユーザーの質問から抽出した検索キーワード（日本語OK）
      【出力】関連ページの詳細内容（タイトル、概要、重要ポイント、リンク付き）
      
      【重要】検索結果から具体的な技術情報、実装方法、設計思想等を抽出して説明すること

  jira_filter_options:
    name: "jira_filter_options"
    description: |
      📋 Jiraで利用可能なフィルター項目一覧を取得します。
      
      【使用場面】
      ・「どんなプロジェクトがある？」
      ・「利用可能なステータスを教えて」
      ・「担当者一覧を見たい」
      ・フィルター検索の前準備
      
      【入力】不要（空文字列でOK）
      【出力】プロジェクト、ステータス、担当者などの選択肢一覧

  jira_filtered_search:
    name: "jira_filtered_search"
    description: |
      🔍 詳細条件でJiraチケットを絞り込み検索します。
      
      【使用場面】
      ・「CTJプロジェクトの完了済みタスク」
      ・「高優先度のバグ一覧」
      ・「○○さん担当の進行中チケット」
      ・「今月作成されたチケット」
      
      【入力】検索キーワード（条件は自動で抽出されます）
      【出力】フィルター条件に一致するチケット一覧

  confluence_filtered_search:
    name: "confluence_filtered_search"
    description: |
      🔍 詳細条件でConfluenceページを絞り込み検索します。
      
      【使用場面】
      ・「特定スペースの仕様書」
      ・「今月更新されたドキュメント」
      ・「特定タイプのページのみ」
      
      【入力】検索キーワード（条件は自動で抽出されます）
      【出力】フィルター条件に一致するページ一覧

  confluence_space_structure:
    name: "confluence_space_structure"
    description: |
      🏗️ Confluenceスペースの全体構造を把握します。
      
      【使用場面】
      ・「どんなドキュメントがあるかざっと知りたい」
      ・「スペースの構造を確認したい」
      ・「ページの階層を理解したい」
      
      【入力】スペースキー（通常は'CLIENTTOMO'）
      【出力】スペース内のページ構造と統計情報

# UI関連メッセージ
ui:
  welcome_message: |
    🤖 こんにちは！仕様書作成支援ボットです

    JiraとConfluenceから必要な情報をすぐに見つけてお答えします。
    以下のような質問をお気軽にどうぞ：

    💡 「ログイン機能の仕様書を探して」
    💡 「UIバグの進捗を教えて」  
    💡 「今月のタスク一覧を見せて」
    💡 「設計書を検索したい」

  processing_message: "🔍 {sources}から「{query}」について検索中です..."
  no_results_message: |
    😅 関連する情報が見つかりませんでした。

    💡 別のキーワードで試してみてください：
    ・より具体的な用語（例：「ログイン」→「認証機能」）
    ・類義語や英語（例：「バグ」→「Bug」「不具合」）
    ・プロジェクト名やチケット番号

  error_message: |
    ❌ 処理中にエラーが発生しました。

    🔄 以下をお試しください：
    ・少し時間をおいてから再実行
    ・シンプルなキーワードで検索
    ・管理者にお問い合わせ

# 応答フォーマットテンプレート
response_templates:
  jira_results: |
    📋 **Jiraチケット分析結果**

    【📌 要約】{count}件のチケットから得られた重要な洞察

    【🔍 詳細分析】
    {results}

    【📊 状況分析】
    - **進捗状況**: 完了率・滞留チケット・ブロッカーの分析
    - **担当者負荷**: 各メンバーのワークロード状況
    - **リスク要因**: 期限遅延・依存関係・技術的課題
    - **品質指標**: バグ率・再発率・修正時間の傾向

    【💡 重要な洞察】
    - **背景・経緯**: なぜこの状況になったのか
    - **影響範囲**: 他の機能・チーム・リリースへの影響
    - **成功要因**: うまくいっている点とその理由
    - **改善機会**: 効率化できる領域の特定

    【🚀 推奨アクション】
    - **immediate（緊急）**: 今すぐ対応すべき事項
    - **short-term（短期）**: 1-2週間で実施すべき施策
    - **long-term（長期）**: 根本的な改善策
    - **prevention（予防）**: 同様の問題を防ぐための対策

    【⚠️ リスクと注意点】
    - 潜在的なブロッカーや依存関係
    - 見落としがちな技術的制約
    - チーム間の調整が必要な事項

    【🔗 参考資料】
    - 詳細なチケット情報のリンク
    - 関連する仕様書・設計書への参照
    - 追加調査すべきキーワード・観点

  confluence_results: |
    📚 **Confluenceドキュメント分析結果**

    【📌 要約】{count}件のドキュメントから抽出した核心的な情報

    【🔍 詳細分析】
    {results}

    【📋 仕様・設計分析】
    - **現在の仕様**: 決定事項と確定済み要件
    - **設計意図**: なぜその設計になったのかの背景
    - **制約条件**: 技術的・ビジネス的な制約事項
    - **変更履歴**: 重要な変更とその理由

    【💡 重要な洞察】
    - **設計思想**: 根本的なアーキテクチャの考え方
    - **ベストプラクティス**: 成功パターンと推奨手法
    - **既知の課題**: 現在把握されている問題点
    - **拡張性**: 将来の機能追加に向けた考慮点

    【🚀 推奨アクション】
    - **実装ガイド**: 具体的な実装手順・チェックポイント
    - **テスト戦略**: 検証すべき項目・テストケース
    - **ドキュメント更新**: 最新化が必要な資料
    - **知識共有**: チーム内で共有すべき重要な知見

    【⚠️ 注意点・制約】
    - 仕様の曖昧な部分・未決定事項
    - 他システムとの連携で注意すべき点
    - パフォーマンス・セキュリティ考慮事項

    【🔗 参考資料】
    - 関連ドキュメントへの詳細リンク
    - 実装サンプル・コード例
    - さらに深掘りすべき調査ポイント

  combined_results: |
    🔍 **統合分析結果**

    【📌 全体要約】
    JiraとConfluenceの情報を統合した包括的な分析結果

    【📋 現状把握】
    {jira_section}
    
    {confluence_section}

    【🔗 情報の関連性分析】
    - **仕様とチケットの対応**: ドキュメントと実装状況の整合性
    - **設計意図の実現度**: 当初の設計思想がどの程度実現できているか
    - **課題の根本原因**: Jiraの課題とConfluenceの仕様の関連性
    - **情報の一貫性**: ドキュメント間の矛盾や齟齬の有無

    【📊 統合的洞察】
    - **全体的な健全性**: プロジェクト・機能の総合的な状況評価
    - **戦略的な示唆**: ビジネス目標達成に向けた重要な観点
    - **組織的な課題**: チーム運営・プロセス改善の機会
    - **技術的な方向性**: アーキテクチャ・技術選定の妥当性

    【🚀 統合的推奨事項】
    - **immediate（緊急対応）**: 仕様とチケットの不整合解消
    - **process（プロセス改善）**: ドキュメント管理・更新フローの最適化
    - **technical（技術改善）**: アーキテクチャ・実装方針の見直し
    - **strategic（戦略改善）**: 長期的な技術戦略・組織体制の改善

    【🎯 Next Steps（具体的行動計画）】
    1. **今週実施**: 最優先で対応すべき事項
    2. **来週計画**: フォローアップ・詳細調査事項  
    3. **月内目標**: 中期的な改善施策
    4. **四半期計画**: 戦略的な取り組み

    【🔗 総合参考資料】
    - 重要なJira/Confluenceリンク集
    - 関連する他プロジェクト・チームの情報
    - 外部ドキュメント・技術資料への参照

  business_insight: |
    💼 **ビジネス価値分析**

    【🎯 ビジネスインパクト】
    - **顧客価値**: この機能・修正がユーザーに与える価値
    - **収益影響**: 売上・コスト・効率性への具体的な影響
    - **競合優位性**: 市場での差別化要因・優位性
    - **リスク軽減**: 回避できるビジネスリスク

    【📈 ROI分析】
    - **投資対効果**: 開発コストに対する期待リターン
    - **時間価値**: 早期リリースの価値・遅延のコスト
    - **機会費用**: 他の選択肢との比較分析
    - **長期価値**: 将来的な拡張性・保守性の価値

    【🎪 ステークホルダー分析】
    - **内部影響**: 開発・運用・サポートチームへの影響
    - **外部影響**: 顧客・パートナー・市場への影響
    - **意思決定者**: キーパーソンと承認プロセス
    - **コミュニケーション**: 報告・共有すべき相手と内容

# エラーハンドリング
error_handling:
  api_connection_error: |
    🔌 外部サービスへの接続に失敗しました。
    ネットワーク接続とAPI設定を確認してください。

  authentication_error: |
    🔐 認証に失敗しました。
    APIトークンと権限設定を確認してください。

  timeout_error: |
    ⏰ 処理がタイムアウトしました。
    検索条件を絞って再試行してください。

  general_error: |
    ❌ 予期しないエラーが発生しました。
    管理者にお問い合わせください。 